name = "contact-form-api"
main = "_functions.js"
compatibility_date = "2023-12-01"

[[kv_namespaces]]
binding = "CONTACTS_KV"
id = "REPLACE_WITH_YOUR_KV_ID"
preview_id = "REPLACE_WITH_YOUR_PREVIEW_KV_ID"